services:
  - type: web
    name: food-order-jtown
    env: python
    region: oregon
    plan: free
    
    buildCommand: >-
     cd food_order_Jtown &&
     pip install --upgrade pip &&
     pip install -r requirements.txt &&
     python manage.py collectstatic --noinput &&
     python manage.py migrate

    startCommand: cd food_order_Jtown && gunicorn food_order_Jtown.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false