services:
  - type: web
    name: food-order-jtown
    env: python
    region: oregon
    plan: free
    
    rootDir: food_order_JTown

    buildCommand: >-
     pip install --upgrade pip &&
     pip install -r requirements.txt &&
     python manage.py collectstatic --noinput &&
     python manage.py migrate

    startCommand: gunicorn food_order_JTown.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: false